/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BannerFiltersInput: { // input type
    and?: Array<NexusGenInputs['BannerFiltersInput'] | null> | null; // [BannerFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    link?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['BannerFiltersInput'] | null; // BannerFiltersInput
    or?: Array<NexusGenInputs['BannerFiltersInput'] | null> | null; // [BannerFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    subTitle?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    title?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  BannerInput: { // input type
    image?: string | null; // ID
    link?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    subTitle?: string | null; // String
    title?: string | null; // String
  }
  BooleanFilterInput: { // input type
    and?: Array<boolean | null> | null; // [Boolean]
    between?: Array<boolean | null> | null; // [Boolean]
    contains?: boolean | null; // Boolean
    containsi?: boolean | null; // Boolean
    endsWith?: boolean | null; // Boolean
    eq?: boolean | null; // Boolean
    eqi?: boolean | null; // Boolean
    gt?: boolean | null; // Boolean
    gte?: boolean | null; // Boolean
    in?: Array<boolean | null> | null; // [Boolean]
    lt?: boolean | null; // Boolean
    lte?: boolean | null; // Boolean
    ne?: boolean | null; // Boolean
    nei?: boolean | null; // Boolean
    not?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    notContains?: boolean | null; // Boolean
    notContainsi?: boolean | null; // Boolean
    notIn?: Array<boolean | null> | null; // [Boolean]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<boolean | null> | null; // [Boolean]
    startsWith?: boolean | null; // Boolean
  }
  CategoryFiltersInput: { // input type
    and?: Array<NexusGenInputs['CategoryFiltersInput'] | null> | null; // [CategoryFiltersInput]
    categories?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
    category?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    metaData?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
    or?: Array<NexusGenInputs['CategoryFiltersInput'] | null> | null; // [CategoryFiltersInput]
    products?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    tags?: NexusGenInputs['TagFiltersInput'] | null; // TagFiltersInput
    uid?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  CategoryInput: { // input type
    categories?: Array<string | null> | null; // [ID]
    category?: string | null; // ID
    image?: string | null; // ID
    metaData?: NexusGenScalars['JSON'] | null; // JSON
    name?: string | null; // String
    products?: Array<string | null> | null; // [ID]
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    tags?: Array<string | null> | null; // [ID]
    uid?: string | null; // String
  }
  ContentReleasesReleaseActionFiltersInput: { // input type
    and?: Array<NexusGenInputs['ContentReleasesReleaseActionFiltersInput'] | null> | null; // [ContentReleasesReleaseActionFiltersInput]
    contentType?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['ContentReleasesReleaseActionFiltersInput'] | null; // ContentReleasesReleaseActionFiltersInput
    or?: Array<NexusGenInputs['ContentReleasesReleaseActionFiltersInput'] | null> | null; // [ContentReleasesReleaseActionFiltersInput]
    release?: NexusGenInputs['ContentReleasesReleaseFiltersInput'] | null; // ContentReleasesReleaseFiltersInput
    type?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  ContentReleasesReleaseActionInput: { // input type
    contentType?: string | null; // String
    release?: string | null; // ID
    type?: NexusGenEnums['ENUM_CONTENTRELEASESRELEASEACTION_TYPE'] | null; // ENUM_CONTENTRELEASESRELEASEACTION_TYPE
  }
  ContentReleasesReleaseFiltersInput: { // input type
    actions?: NexusGenInputs['ContentReleasesReleaseActionFiltersInput'] | null; // ContentReleasesReleaseActionFiltersInput
    and?: Array<NexusGenInputs['ContentReleasesReleaseFiltersInput'] | null> | null; // [ContentReleasesReleaseFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ContentReleasesReleaseFiltersInput'] | null; // ContentReleasesReleaseFiltersInput
    or?: Array<NexusGenInputs['ContentReleasesReleaseFiltersInput'] | null> | null; // [ContentReleasesReleaseFiltersInput]
    releasedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  ContentReleasesReleaseInput: { // input type
    actions?: Array<string | null> | null; // [ID]
    name?: string | null; // String
    releasedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateFilterInput: { // input type
    and?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    between?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    contains?: NexusGenScalars['Date'] | null; // Date
    containsi?: NexusGenScalars['Date'] | null; // Date
    endsWith?: NexusGenScalars['Date'] | null; // Date
    eq?: NexusGenScalars['Date'] | null; // Date
    eqi?: NexusGenScalars['Date'] | null; // Date
    gt?: NexusGenScalars['Date'] | null; // Date
    gte?: NexusGenScalars['Date'] | null; // Date
    in?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    lt?: NexusGenScalars['Date'] | null; // Date
    lte?: NexusGenScalars['Date'] | null; // Date
    ne?: NexusGenScalars['Date'] | null; // Date
    nei?: NexusGenScalars['Date'] | null; // Date
    not?: NexusGenInputs['DateFilterInput'] | null; // DateFilterInput
    notContains?: NexusGenScalars['Date'] | null; // Date
    notContainsi?: NexusGenScalars['Date'] | null; // Date
    notIn?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    startsWith?: NexusGenScalars['Date'] | null; // Date
  }
  DateTimeFilterInput: { // input type
    and?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    between?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    contains?: NexusGenScalars['DateTime'] | null; // DateTime
    containsi?: NexusGenScalars['DateTime'] | null; // DateTime
    endsWith?: NexusGenScalars['DateTime'] | null; // DateTime
    eq?: NexusGenScalars['DateTime'] | null; // DateTime
    eqi?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    ne?: NexusGenScalars['DateTime'] | null; // DateTime
    nei?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    notContains?: NexusGenScalars['DateTime'] | null; // DateTime
    notContainsi?: NexusGenScalars['DateTime'] | null; // DateTime
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    startsWith?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  FileInfoInput: { // input type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    name?: string | null; // String
  }
  FloatFilterInput: { // input type
    and?: Array<number | null> | null; // [Float]
    between?: Array<number | null> | null; // [Float]
    contains?: number | null; // Float
    containsi?: number | null; // Float
    endsWith?: number | null; // Float
    eq?: number | null; // Float
    eqi?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: Array<number | null> | null; // [Float]
    lt?: number | null; // Float
    lte?: number | null; // Float
    ne?: number | null; // Float
    nei?: number | null; // Float
    not?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    notContains?: number | null; // Float
    notContainsi?: number | null; // Float
    notIn?: Array<number | null> | null; // [Float]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<number | null> | null; // [Float]
    startsWith?: number | null; // Float
  }
  I18NLocaleFiltersInput: { // input type
    and?: Array<NexusGenInputs['I18NLocaleFiltersInput'] | null> | null; // [I18NLocaleFiltersInput]
    code?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['I18NLocaleFiltersInput'] | null; // I18NLocaleFiltersInput
    or?: Array<NexusGenInputs['I18NLocaleFiltersInput'] | null> | null; // [I18NLocaleFiltersInput]
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  I18NLocaleInput: { // input type
    code?: string | null; // String
    name?: string | null; // String
  }
  IDFilterInput: { // input type
    and?: Array<string | null> | null; // [ID]
    between?: Array<string | null> | null; // [ID]
    contains?: string | null; // ID
    containsi?: string | null; // ID
    endsWith?: string | null; // ID
    eq?: string | null; // ID
    eqi?: string | null; // ID
    gt?: string | null; // ID
    gte?: string | null; // ID
    in?: Array<string | null> | null; // [ID]
    lt?: string | null; // ID
    lte?: string | null; // ID
    ne?: string | null; // ID
    nei?: string | null; // ID
    not?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    notContains?: string | null; // ID
    notContainsi?: string | null; // ID
    notIn?: Array<string | null> | null; // [ID]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<string | null> | null; // [ID]
    startsWith?: string | null; // ID
  }
  IntFilterInput: { // input type
    and?: Array<number | null> | null; // [Int]
    between?: Array<number | null> | null; // [Int]
    contains?: number | null; // Int
    containsi?: number | null; // Int
    endsWith?: number | null; // Int
    eq?: number | null; // Int
    eqi?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    ne?: number | null; // Int
    nei?: number | null; // Int
    not?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    notContains?: number | null; // Int
    notContainsi?: number | null; // Int
    notIn?: Array<number | null> | null; // [Int]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<number | null> | null; // [Int]
    startsWith?: number | null; // Int
  }
  JSONFilterInput: { // input type
    and?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    between?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    contains?: NexusGenScalars['JSON'] | null; // JSON
    containsi?: NexusGenScalars['JSON'] | null; // JSON
    endsWith?: NexusGenScalars['JSON'] | null; // JSON
    eq?: NexusGenScalars['JSON'] | null; // JSON
    eqi?: NexusGenScalars['JSON'] | null; // JSON
    gt?: NexusGenScalars['JSON'] | null; // JSON
    gte?: NexusGenScalars['JSON'] | null; // JSON
    in?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    lt?: NexusGenScalars['JSON'] | null; // JSON
    lte?: NexusGenScalars['JSON'] | null; // JSON
    ne?: NexusGenScalars['JSON'] | null; // JSON
    nei?: NexusGenScalars['JSON'] | null; // JSON
    not?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    notContains?: NexusGenScalars['JSON'] | null; // JSON
    notContainsi?: NexusGenScalars['JSON'] | null; // JSON
    notIn?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    startsWith?: NexusGenScalars['JSON'] | null; // JSON
  }
  LongFilterInput: { // input type
    and?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    between?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    contains?: NexusGenScalars['Long'] | null; // Long
    containsi?: NexusGenScalars['Long'] | null; // Long
    endsWith?: NexusGenScalars['Long'] | null; // Long
    eq?: NexusGenScalars['Long'] | null; // Long
    eqi?: NexusGenScalars['Long'] | null; // Long
    gt?: NexusGenScalars['Long'] | null; // Long
    gte?: NexusGenScalars['Long'] | null; // Long
    in?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    lt?: NexusGenScalars['Long'] | null; // Long
    lte?: NexusGenScalars['Long'] | null; // Long
    ne?: NexusGenScalars['Long'] | null; // Long
    nei?: NexusGenScalars['Long'] | null; // Long
    not?: NexusGenInputs['LongFilterInput'] | null; // LongFilterInput
    notContains?: NexusGenScalars['Long'] | null; // Long
    notContainsi?: NexusGenScalars['Long'] | null; // Long
    notIn?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    startsWith?: NexusGenScalars['Long'] | null; // Long
  }
  PaginationArg: { // input type
    limit?: number | null; // Int
    page?: number | null; // Int
    pageSize?: number | null; // Int
    start?: number | null; // Int
  }
  ProductFiltersInput: { // input type
    and?: Array<NexusGenInputs['ProductFiltersInput'] | null> | null; // [ProductFiltersInput]
    category?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    discount?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    mrp?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    not?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    or?: Array<NexusGenInputs['ProductFiltersInput'] | null> | null; // [ProductFiltersInput]
    outOfStock?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    productInfo?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    rating?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    slug?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    sp?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    tags?: NexusGenInputs['TagFiltersInput'] | null; // TagFiltersInput
    title?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  ProductInput: { // input type
    category?: string | null; // ID
    description?: string | null; // String
    discount?: number | null; // Float
    mrp?: number | null; // Float
    otherImages?: Array<string | null> | null; // [ID]
    outOfStock?: boolean | null; // Boolean
    productImage?: Array<string | null> | null; // [ID]
    productInfo?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    rating?: number | null; // Float
    slug?: string | null; // String
    sp?: number | null; // Float
    tags?: Array<string | null> | null; // [ID]
    title?: string | null; // String
  }
  ServiceAvailableAtFiltersInput: { // input type
    and?: Array<NexusGenInputs['ServiceAvailableAtFiltersInput'] | null> | null; // [ServiceAvailableAtFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['ServiceAvailableAtFiltersInput'] | null; // ServiceAvailableAtFiltersInput
    or?: Array<NexusGenInputs['ServiceAvailableAtFiltersInput'] | null> | null; // [ServiceAvailableAtFiltersInput]
    place?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    uid?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  ServiceAvailableAtInput: { // input type
    image?: string | null; // ID
    place?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    uid?: string | null; // String
  }
  StringFilterInput: { // input type
    and?: Array<string | null> | null; // [String]
    between?: Array<string | null> | null; // [String]
    contains?: string | null; // String
    containsi?: string | null; // String
    endsWith?: string | null; // String
    eq?: string | null; // String
    eqi?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    ne?: string | null; // String
    nei?: string | null; // String
    not?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    notContains?: string | null; // String
    notContainsi?: string | null; // String
    notIn?: Array<string | null> | null; // [String]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  TagFiltersInput: { // input type
    and?: Array<NexusGenInputs['TagFiltersInput'] | null> | null; // [TagFiltersInput]
    categories?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['TagFiltersInput'] | null; // TagFiltersInput
    or?: Array<NexusGenInputs['TagFiltersInput'] | null> | null; // [TagFiltersInput]
    products?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    tagName?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  TagInput: { // input type
    categories?: Array<string | null> | null; // [ID]
    icon?: string | null; // ID
    products?: Array<string | null> | null; // [ID]
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    tagName?: string | null; // String
  }
  TessssssstFiltersInput: { // input type
    and?: Array<NexusGenInputs['TessssssstFiltersInput'] | null> | null; // [TessssssstFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['TessssssstFiltersInput'] | null; // TessssssstFiltersInput
    or?: Array<NexusGenInputs['TessssssstFiltersInput'] | null> | null; // [TessssssstFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    test?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  TessssssstInput: { // input type
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    test?: string | null; // String
  }
  TimeFilterInput: { // input type
    and?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    between?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    contains?: NexusGenScalars['Time'] | null; // Time
    containsi?: NexusGenScalars['Time'] | null; // Time
    endsWith?: NexusGenScalars['Time'] | null; // Time
    eq?: NexusGenScalars['Time'] | null; // Time
    eqi?: NexusGenScalars['Time'] | null; // Time
    gt?: NexusGenScalars['Time'] | null; // Time
    gte?: NexusGenScalars['Time'] | null; // Time
    in?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    lt?: NexusGenScalars['Time'] | null; // Time
    lte?: NexusGenScalars['Time'] | null; // Time
    ne?: NexusGenScalars['Time'] | null; // Time
    nei?: NexusGenScalars['Time'] | null; // Time
    not?: NexusGenInputs['TimeFilterInput'] | null; // TimeFilterInput
    notContains?: NexusGenScalars['Time'] | null; // Time
    notContainsi?: NexusGenScalars['Time'] | null; // Time
    notIn?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    startsWith?: NexusGenScalars['Time'] | null; // Time
  }
  UploadFileFiltersInput: { // input type
    alternativeText?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    and?: Array<NexusGenInputs['UploadFileFiltersInput'] | null> | null; // [UploadFileFiltersInput]
    caption?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    ext?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    folder?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    folderPath?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    formats?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    hash?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    height?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    mime?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
    or?: Array<NexusGenInputs['UploadFileFiltersInput'] | null> | null; // [UploadFileFiltersInput]
    previewUrl?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider_metadata?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    size?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    url?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    width?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
  }
  UploadFileInput: { // input type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    ext?: string | null; // String
    folder?: string | null; // ID
    folderPath?: string | null; // String
    formats?: NexusGenScalars['JSON'] | null; // JSON
    hash?: string | null; // String
    height?: number | null; // Int
    mime?: string | null; // String
    name?: string | null; // String
    previewUrl?: string | null; // String
    provider?: string | null; // String
    provider_metadata?: NexusGenScalars['JSON'] | null; // JSON
    size?: number | null; // Float
    url?: string | null; // String
    width?: number | null; // Int
  }
  UploadFolderFiltersInput: { // input type
    and?: Array<NexusGenInputs['UploadFolderFiltersInput'] | null> | null; // [UploadFolderFiltersInput]
    children?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    files?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    or?: Array<NexusGenInputs['UploadFolderFiltersInput'] | null> | null; // [UploadFolderFiltersInput]
    parent?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    path?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    pathId?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  UploadFolderInput: { // input type
    children?: Array<string | null> | null; // [ID]
    files?: Array<string | null> | null; // [ID]
    name?: string | null; // String
    parent?: string | null; // ID
    path?: string | null; // String
    pathId?: number | null; // Int
  }
  UsersPermissionsLoginInput: { // input type
    identifier: string; // String!
    password: string; // String!
    provider: string; // String!
  }
  UsersPermissionsPermissionFiltersInput: { // input type
    action?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    and?: Array<NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null> | null; // [UsersPermissionsPermissionFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null> | null; // [UsersPermissionsPermissionFiltersInput]
    role?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  UsersPermissionsPermissionInput: { // input type
    action?: string | null; // String
    role?: string | null; // ID
  }
  UsersPermissionsRegisterInput: { // input type
    email: string; // String!
    password: string; // String!
    username: string; // String!
  }
  UsersPermissionsRoleFiltersInput: { // input type
    and?: Array<NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null> | null; // [UsersPermissionsRoleFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null> | null; // [UsersPermissionsRoleFiltersInput]
    permissions?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
    type?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    users?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
  }
  UsersPermissionsRoleInput: { // input type
    description?: string | null; // String
    name?: string | null; // String
    permissions?: Array<string | null> | null; // [ID]
    type?: string | null; // String
    users?: Array<string | null> | null; // [ID]
  }
  UsersPermissionsUserFiltersInput: { // input type
    and?: Array<NexusGenInputs['UsersPermissionsUserFiltersInput'] | null> | null; // [UsersPermissionsUserFiltersInput]
    blocked?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    confirmationToken?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    confirmed?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    dateOfBirth?: NexusGenInputs['DateFilterInput'] | null; // DateFilterInput
    email?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsUserFiltersInput'] | null> | null; // [UsersPermissionsUserFiltersInput]
    password?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    resetPasswordToken?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    role?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    username?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
  }
  UsersPermissionsUserInput: { // input type
    blocked?: boolean | null; // Boolean
    confirmationToken?: string | null; // String
    confirmed?: boolean | null; // Boolean
    dateOfBirth?: NexusGenScalars['Date'] | null; // Date
    email?: string | null; // String
    password?: string | null; // String
    provider?: string | null; // String
    resetPasswordToken?: string | null; // String
    role?: string | null; // ID
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
  ENUM_CONTENTRELEASESRELEASEACTION_TYPE: "publish" | "unpublish"
  PublicationState: "live" | "preview"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  DateTime: any
  I18NLocaleCode: any
  JSON: any
  Long: any
  Time: any
  Upload: any
}

export interface NexusGenObjects {
  Banner: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    link?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    subTitle?: string | null; // String
    title?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BannerEntity: {};
  BannerEntityResponse: {};
  BannerEntityResponseCollection: {};
  BannerRelationResponseCollection: {};
  Category: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    metaData?: NexusGenScalars['JSON'] | null; // JSON
    name: string; // String!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    uid?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryEntity: {};
  CategoryEntityResponse: {};
  CategoryEntityResponseCollection: {};
  CategoryRelationResponseCollection: {};
  ContentReleasesRelease: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    releasedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ContentReleasesReleaseAction: { // root type
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    type: NexusGenEnums['ENUM_CONTENTRELEASESRELEASEACTION_TYPE']; // ENUM_CONTENTRELEASESRELEASEACTION_TYPE!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ContentReleasesReleaseActionEntity: {};
  ContentReleasesReleaseActionEntityResponse: {};
  ContentReleasesReleaseActionEntityResponseCollection: {};
  ContentReleasesReleaseActionRelationResponseCollection: {};
  ContentReleasesReleaseEntity: {};
  ContentReleasesReleaseEntityResponse: {};
  ContentReleasesReleaseEntityResponseCollection: {};
  ContentReleasesReleaseRelationResponseCollection: {};
  Error: { // root type
    message?: string | null; // String
  }
  I18NLocale: { // root type
    code?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  I18NLocaleEntity: {};
  I18NLocaleEntityResponse: {};
  I18NLocaleEntityResponseCollection: {};
  I18NLocaleRelationResponseCollection: {};
  Mutation: {};
  Pagination: { // root type
    page: number; // Int!
    pageCount: number; // Int!
    pageSize: number; // Int!
    total: number; // Int!
  }
  Product: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    discount?: number | null; // Float
    mrp?: number | null; // Float
    outOfStock: boolean; // Boolean!
    productInfo?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    rating?: number | null; // Float
    slug: string; // String!
    sp?: number | null; // Float
    title?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ProductEntity: {};
  ProductEntityResponse: {};
  ProductEntityResponseCollection: {};
  ProductRelationResponseCollection: {};
  Query: {};
  ResponseCollectionMeta: {};
  ServiceAvailableAt: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    place?: string | null; // String
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    uid?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ServiceAvailableAtEntity: {};
  ServiceAvailableAtEntityResponse: {};
  ServiceAvailableAtEntityResponseCollection: {};
  ServiceAvailableAtRelationResponseCollection: {};
  Tag: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    tagName?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  TagEntity: {};
  TagEntityResponse: {};
  TagEntityResponseCollection: {};
  TagRelationResponseCollection: {};
  Tessssssst: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    test?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  TessssssstEntity: {};
  TessssssstEntityResponse: {};
  TessssssstEntityResponseCollection: {};
  TessssssstRelationResponseCollection: {};
  UploadFile: { // root type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    ext?: string | null; // String
    formats?: NexusGenScalars['JSON'] | null; // JSON
    hash: string; // String!
    height?: number | null; // Int
    mime: string; // String!
    name: string; // String!
    previewUrl?: string | null; // String
    provider: string; // String!
    provider_metadata?: NexusGenScalars['JSON'] | null; // JSON
    size: number; // Float!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    url: string; // String!
    width?: number | null; // Int
  }
  UploadFileEntity: {};
  UploadFileEntityResponse: {};
  UploadFileEntityResponseCollection: {};
  UploadFileRelationResponseCollection: {};
  UploadFolder: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    path: string; // String!
    pathId: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UploadFolderEntity: {};
  UploadFolderEntityResponse: {};
  UploadFolderEntityResponseCollection: {};
  UploadFolderRelationResponseCollection: {};
  UsersPermissionsCreateRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsDeleteRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsLoginPayload: { // root type
    jwt?: string | null; // String
    user: NexusGenRootTypes['UsersPermissionsMe']; // UsersPermissionsMe!
  }
  UsersPermissionsMe: { // root type
    blocked?: boolean | null; // Boolean
    confirmed?: boolean | null; // Boolean
    email?: string | null; // String
    id: string; // ID!
    role?: NexusGenRootTypes['UsersPermissionsMeRole'] | null; // UsersPermissionsMeRole
    username: string; // String!
  }
  UsersPermissionsMeRole: { // root type
    description?: string | null; // String
    id: string; // ID!
    name: string; // String!
    type?: string | null; // String
  }
  UsersPermissionsPasswordPayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsPermission: { // root type
    action: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsPermissionEntity: {};
  UsersPermissionsPermissionEntityResponse: {};
  UsersPermissionsPermissionEntityResponseCollection: {};
  UsersPermissionsPermissionRelationResponseCollection: {};
  UsersPermissionsRole: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    type?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsRoleEntity: {};
  UsersPermissionsRoleEntityResponse: {};
  UsersPermissionsRoleEntityResponseCollection: {};
  UsersPermissionsRoleRelationResponseCollection: {};
  UsersPermissionsUpdateRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsUser: { // root type
    blocked?: boolean | null; // Boolean
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    dateOfBirth: NexusGenScalars['Date']; // Date!
    email: string; // String!
    provider?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    username: string; // String!
  }
  UsersPermissionsUserEntity: {};
  UsersPermissionsUserEntityResponse: {};
  UsersPermissionsUserEntityResponseCollection: {};
  UsersPermissionsUserRelationResponseCollection: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
  GenericMorph: NexusGenRootTypes['Banner'] | NexusGenRootTypes['Category'] | NexusGenRootTypes['ContentReleasesRelease'] | NexusGenRootTypes['ContentReleasesReleaseAction'] | NexusGenRootTypes['I18NLocale'] | NexusGenRootTypes['Product'] | NexusGenRootTypes['ServiceAvailableAt'] | NexusGenRootTypes['Tag'] | NexusGenRootTypes['Tessssssst'] | NexusGenRootTypes['UploadFile'] | NexusGenRootTypes['UploadFolder'] | NexusGenRootTypes['UsersPermissionsPermission'] | NexusGenRootTypes['UsersPermissionsRole'] | NexusGenRootTypes['UsersPermissionsUser'];
}

export type NexusGenRootTypes = NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Banner: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    image: NexusGenRootTypes['UploadFileEntityResponse']; // UploadFileEntityResponse!
    link: string | null; // String
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    subTitle: string | null; // String
    title: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BannerEntity: { // field return type
    attributes: NexusGenRootTypes['Banner'] | null; // Banner
    id: string | null; // ID
  }
  BannerEntityResponse: { // field return type
    data: NexusGenRootTypes['BannerEntity'] | null; // BannerEntity
  }
  BannerEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['BannerEntity'][]; // [BannerEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  BannerRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['BannerEntity'][]; // [BannerEntity!]!
  }
  Category: { // field return type
    categories: NexusGenRootTypes['CategoryRelationResponseCollection'] | null; // CategoryRelationResponseCollection
    category: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    image: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    metaData: NexusGenScalars['JSON'] | null; // JSON
    name: string; // String!
    products: NexusGenRootTypes['ProductRelationResponseCollection'] | null; // ProductRelationResponseCollection
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    tags: NexusGenRootTypes['TagRelationResponseCollection'] | null; // TagRelationResponseCollection
    uid: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryEntity: { // field return type
    attributes: NexusGenRootTypes['Category'] | null; // Category
    id: string | null; // ID
  }
  CategoryEntityResponse: { // field return type
    data: NexusGenRootTypes['CategoryEntity'] | null; // CategoryEntity
  }
  CategoryEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['CategoryEntity'][]; // [CategoryEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  CategoryRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['CategoryEntity'][]; // [CategoryEntity!]!
  }
  ContentReleasesRelease: { // field return type
    actions: NexusGenRootTypes['ContentReleasesReleaseActionRelationResponseCollection'] | null; // ContentReleasesReleaseActionRelationResponseCollection
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    releasedAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ContentReleasesReleaseAction: { // field return type
    contentType: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    entry: NexusGenRootTypes['GenericMorph'] | null; // GenericMorph
    release: NexusGenRootTypes['ContentReleasesReleaseEntityResponse'] | null; // ContentReleasesReleaseEntityResponse
    type: NexusGenEnums['ENUM_CONTENTRELEASESRELEASEACTION_TYPE']; // ENUM_CONTENTRELEASESRELEASEACTION_TYPE!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ContentReleasesReleaseActionEntity: { // field return type
    attributes: NexusGenRootTypes['ContentReleasesReleaseAction'] | null; // ContentReleasesReleaseAction
    id: string | null; // ID
  }
  ContentReleasesReleaseActionEntityResponse: { // field return type
    data: NexusGenRootTypes['ContentReleasesReleaseActionEntity'] | null; // ContentReleasesReleaseActionEntity
  }
  ContentReleasesReleaseActionEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['ContentReleasesReleaseActionEntity'][]; // [ContentReleasesReleaseActionEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  ContentReleasesReleaseActionRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['ContentReleasesReleaseActionEntity'][]; // [ContentReleasesReleaseActionEntity!]!
  }
  ContentReleasesReleaseEntity: { // field return type
    attributes: NexusGenRootTypes['ContentReleasesRelease'] | null; // ContentReleasesRelease
    id: string | null; // ID
  }
  ContentReleasesReleaseEntityResponse: { // field return type
    data: NexusGenRootTypes['ContentReleasesReleaseEntity'] | null; // ContentReleasesReleaseEntity
  }
  ContentReleasesReleaseEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['ContentReleasesReleaseEntity'][]; // [ContentReleasesReleaseEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  ContentReleasesReleaseRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['ContentReleasesReleaseEntity'][]; // [ContentReleasesReleaseEntity!]!
  }
  Error: { // field return type
    code: string; // String!
    message: string | null; // String
  }
  I18NLocale: { // field return type
    code: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  I18NLocaleEntity: { // field return type
    attributes: NexusGenRootTypes['I18NLocale'] | null; // I18NLocale
    id: string | null; // ID
  }
  I18NLocaleEntityResponse: { // field return type
    data: NexusGenRootTypes['I18NLocaleEntity'] | null; // I18NLocaleEntity
  }
  I18NLocaleEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['I18NLocaleEntity'][]; // [I18NLocaleEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  I18NLocaleRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['I18NLocaleEntity'][]; // [I18NLocaleEntity!]!
  }
  Mutation: { // field return type
    changePassword: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    createBanner: NexusGenRootTypes['BannerEntityResponse'] | null; // BannerEntityResponse
    createCategory: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    createContentReleasesRelease: NexusGenRootTypes['ContentReleasesReleaseEntityResponse'] | null; // ContentReleasesReleaseEntityResponse
    createContentReleasesReleaseAction: NexusGenRootTypes['ContentReleasesReleaseActionEntityResponse'] | null; // ContentReleasesReleaseActionEntityResponse
    createProduct: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    createServiceAvailableAt: NexusGenRootTypes['ServiceAvailableAtEntityResponse'] | null; // ServiceAvailableAtEntityResponse
    createTag: NexusGenRootTypes['TagEntityResponse'] | null; // TagEntityResponse
    createTessssssst: NexusGenRootTypes['TessssssstEntityResponse'] | null; // TessssssstEntityResponse
    createUploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    createUploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    createUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsCreateRolePayload'] | null; // UsersPermissionsCreateRolePayload
    createUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    deleteBanner: NexusGenRootTypes['BannerEntityResponse'] | null; // BannerEntityResponse
    deleteCategory: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    deleteContentReleasesRelease: NexusGenRootTypes['ContentReleasesReleaseEntityResponse'] | null; // ContentReleasesReleaseEntityResponse
    deleteContentReleasesReleaseAction: NexusGenRootTypes['ContentReleasesReleaseActionEntityResponse'] | null; // ContentReleasesReleaseActionEntityResponse
    deleteProduct: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    deleteServiceAvailableAt: NexusGenRootTypes['ServiceAvailableAtEntityResponse'] | null; // ServiceAvailableAtEntityResponse
    deleteTag: NexusGenRootTypes['TagEntityResponse'] | null; // TagEntityResponse
    deleteTessssssst: NexusGenRootTypes['TessssssstEntityResponse'] | null; // TessssssstEntityResponse
    deleteUploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    deleteUploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    deleteUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsDeleteRolePayload'] | null; // UsersPermissionsDeleteRolePayload
    deleteUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    emailConfirmation: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    forgotPassword: NexusGenRootTypes['UsersPermissionsPasswordPayload'] | null; // UsersPermissionsPasswordPayload
    login: NexusGenRootTypes['UsersPermissionsLoginPayload']; // UsersPermissionsLoginPayload!
    multipleUpload: Array<NexusGenRootTypes['UploadFileEntityResponse'] | null>; // [UploadFileEntityResponse]!
    register: NexusGenRootTypes['UsersPermissionsLoginPayload']; // UsersPermissionsLoginPayload!
    removeFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    resetPassword: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    updateBanner: NexusGenRootTypes['BannerEntityResponse'] | null; // BannerEntityResponse
    updateCategory: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    updateContentReleasesRelease: NexusGenRootTypes['ContentReleasesReleaseEntityResponse'] | null; // ContentReleasesReleaseEntityResponse
    updateContentReleasesReleaseAction: NexusGenRootTypes['ContentReleasesReleaseActionEntityResponse'] | null; // ContentReleasesReleaseActionEntityResponse
    updateFileInfo: NexusGenRootTypes['UploadFileEntityResponse']; // UploadFileEntityResponse!
    updateProduct: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    updateServiceAvailableAt: NexusGenRootTypes['ServiceAvailableAtEntityResponse'] | null; // ServiceAvailableAtEntityResponse
    updateTag: NexusGenRootTypes['TagEntityResponse'] | null; // TagEntityResponse
    updateTessssssst: NexusGenRootTypes['TessssssstEntityResponse'] | null; // TessssssstEntityResponse
    updateUploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    updateUploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    updateUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsUpdateRolePayload'] | null; // UsersPermissionsUpdateRolePayload
    updateUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    upload: NexusGenRootTypes['UploadFileEntityResponse']; // UploadFileEntityResponse!
  }
  Pagination: { // field return type
    page: number; // Int!
    pageCount: number; // Int!
    pageSize: number; // Int!
    total: number; // Int!
  }
  Product: { // field return type
    category: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    discount: number | null; // Float
    mrp: number | null; // Float
    otherImages: NexusGenRootTypes['UploadFileRelationResponseCollection'] | null; // UploadFileRelationResponseCollection
    outOfStock: boolean; // Boolean!
    productImage: NexusGenRootTypes['UploadFileRelationResponseCollection']; // UploadFileRelationResponseCollection!
    productInfo: string | null; // String
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    rating: number | null; // Float
    slug: string; // String!
    sp: number | null; // Float
    tags: NexusGenRootTypes['TagRelationResponseCollection'] | null; // TagRelationResponseCollection
    title: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ProductEntity: { // field return type
    attributes: NexusGenRootTypes['Product'] | null; // Product
    id: string | null; // ID
  }
  ProductEntityResponse: { // field return type
    data: NexusGenRootTypes['ProductEntity'] | null; // ProductEntity
  }
  ProductEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['ProductEntity'][]; // [ProductEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  ProductRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['ProductEntity'][]; // [ProductEntity!]!
  }
  Query: { // field return type
    banner: NexusGenRootTypes['BannerEntityResponse'] | null; // BannerEntityResponse
    banners: NexusGenRootTypes['BannerEntityResponseCollection'] | null; // BannerEntityResponseCollection
    categories: NexusGenRootTypes['CategoryEntityResponseCollection'] | null; // CategoryEntityResponseCollection
    category: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    contentReleasesRelease: NexusGenRootTypes['ContentReleasesReleaseEntityResponse'] | null; // ContentReleasesReleaseEntityResponse
    contentReleasesReleaseAction: NexusGenRootTypes['ContentReleasesReleaseActionEntityResponse'] | null; // ContentReleasesReleaseActionEntityResponse
    contentReleasesReleaseActions: NexusGenRootTypes['ContentReleasesReleaseActionEntityResponseCollection'] | null; // ContentReleasesReleaseActionEntityResponseCollection
    contentReleasesReleases: NexusGenRootTypes['ContentReleasesReleaseEntityResponseCollection'] | null; // ContentReleasesReleaseEntityResponseCollection
    i18NLocale: NexusGenRootTypes['I18NLocaleEntityResponse'] | null; // I18NLocaleEntityResponse
    i18NLocales: NexusGenRootTypes['I18NLocaleEntityResponseCollection'] | null; // I18NLocaleEntityResponseCollection
    me: NexusGenRootTypes['UsersPermissionsMe'] | null; // UsersPermissionsMe
    product: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    products: NexusGenRootTypes['ProductEntityResponseCollection'] | null; // ProductEntityResponseCollection
    serviceAvailableAt: NexusGenRootTypes['ServiceAvailableAtEntityResponse'] | null; // ServiceAvailableAtEntityResponse
    serviceAvailableAts: NexusGenRootTypes['ServiceAvailableAtEntityResponseCollection'] | null; // ServiceAvailableAtEntityResponseCollection
    tag: NexusGenRootTypes['TagEntityResponse'] | null; // TagEntityResponse
    tags: NexusGenRootTypes['TagEntityResponseCollection'] | null; // TagEntityResponseCollection
    tessssssst: NexusGenRootTypes['TessssssstEntityResponse'] | null; // TessssssstEntityResponse
    tesssssssts: NexusGenRootTypes['TessssssstEntityResponseCollection'] | null; // TessssssstEntityResponseCollection
    uploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    uploadFiles: NexusGenRootTypes['UploadFileEntityResponseCollection'] | null; // UploadFileEntityResponseCollection
    uploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    uploadFolders: NexusGenRootTypes['UploadFolderEntityResponseCollection'] | null; // UploadFolderEntityResponseCollection
    usersPermissionsRole: NexusGenRootTypes['UsersPermissionsRoleEntityResponse'] | null; // UsersPermissionsRoleEntityResponse
    usersPermissionsRoles: NexusGenRootTypes['UsersPermissionsRoleEntityResponseCollection'] | null; // UsersPermissionsRoleEntityResponseCollection
    usersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse'] | null; // UsersPermissionsUserEntityResponse
    usersPermissionsUsers: NexusGenRootTypes['UsersPermissionsUserEntityResponseCollection'] | null; // UsersPermissionsUserEntityResponseCollection
  }
  ResponseCollectionMeta: { // field return type
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  ServiceAvailableAt: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    image: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    place: string | null; // String
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    uid: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ServiceAvailableAtEntity: { // field return type
    attributes: NexusGenRootTypes['ServiceAvailableAt'] | null; // ServiceAvailableAt
    id: string | null; // ID
  }
  ServiceAvailableAtEntityResponse: { // field return type
    data: NexusGenRootTypes['ServiceAvailableAtEntity'] | null; // ServiceAvailableAtEntity
  }
  ServiceAvailableAtEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['ServiceAvailableAtEntity'][]; // [ServiceAvailableAtEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  ServiceAvailableAtRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['ServiceAvailableAtEntity'][]; // [ServiceAvailableAtEntity!]!
  }
  Tag: { // field return type
    categories: NexusGenRootTypes['CategoryRelationResponseCollection'] | null; // CategoryRelationResponseCollection
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    icon: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    products: NexusGenRootTypes['ProductRelationResponseCollection'] | null; // ProductRelationResponseCollection
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    tagName: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  TagEntity: { // field return type
    attributes: NexusGenRootTypes['Tag'] | null; // Tag
    id: string | null; // ID
  }
  TagEntityResponse: { // field return type
    data: NexusGenRootTypes['TagEntity'] | null; // TagEntity
  }
  TagEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['TagEntity'][]; // [TagEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  TagRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['TagEntity'][]; // [TagEntity!]!
  }
  Tessssssst: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    test: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  TessssssstEntity: { // field return type
    attributes: NexusGenRootTypes['Tessssssst'] | null; // Tessssssst
    id: string | null; // ID
  }
  TessssssstEntityResponse: { // field return type
    data: NexusGenRootTypes['TessssssstEntity'] | null; // TessssssstEntity
  }
  TessssssstEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['TessssssstEntity'][]; // [TessssssstEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  TessssssstRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['TessssssstEntity'][]; // [TessssssstEntity!]!
  }
  UploadFile: { // field return type
    alternativeText: string | null; // String
    caption: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    ext: string | null; // String
    formats: NexusGenScalars['JSON'] | null; // JSON
    hash: string; // String!
    height: number | null; // Int
    mime: string; // String!
    name: string; // String!
    previewUrl: string | null; // String
    provider: string; // String!
    provider_metadata: NexusGenScalars['JSON'] | null; // JSON
    related: Array<NexusGenRootTypes['GenericMorph'] | null> | null; // [GenericMorph]
    size: number; // Float!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    url: string; // String!
    width: number | null; // Int
  }
  UploadFileEntity: { // field return type
    attributes: NexusGenRootTypes['UploadFile'] | null; // UploadFile
    id: string | null; // ID
  }
  UploadFileEntityResponse: { // field return type
    data: NexusGenRootTypes['UploadFileEntity'] | null; // UploadFileEntity
  }
  UploadFileEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFileEntity'][]; // [UploadFileEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UploadFileRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFileEntity'][]; // [UploadFileEntity!]!
  }
  UploadFolder: { // field return type
    children: NexusGenRootTypes['UploadFolderRelationResponseCollection'] | null; // UploadFolderRelationResponseCollection
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    files: NexusGenRootTypes['UploadFileRelationResponseCollection'] | null; // UploadFileRelationResponseCollection
    name: string; // String!
    parent: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    path: string; // String!
    pathId: number; // Int!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UploadFolderEntity: { // field return type
    attributes: NexusGenRootTypes['UploadFolder'] | null; // UploadFolder
    id: string | null; // ID
  }
  UploadFolderEntityResponse: { // field return type
    data: NexusGenRootTypes['UploadFolderEntity'] | null; // UploadFolderEntity
  }
  UploadFolderEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFolderEntity'][]; // [UploadFolderEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UploadFolderRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFolderEntity'][]; // [UploadFolderEntity!]!
  }
  UsersPermissionsCreateRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsDeleteRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsLoginPayload: { // field return type
    jwt: string | null; // String
    user: NexusGenRootTypes['UsersPermissionsMe']; // UsersPermissionsMe!
  }
  UsersPermissionsMe: { // field return type
    blocked: boolean | null; // Boolean
    confirmed: boolean | null; // Boolean
    email: string | null; // String
    id: string; // ID!
    role: NexusGenRootTypes['UsersPermissionsMeRole'] | null; // UsersPermissionsMeRole
    username: string; // String!
  }
  UsersPermissionsMeRole: { // field return type
    description: string | null; // String
    id: string; // ID!
    name: string; // String!
    type: string | null; // String
  }
  UsersPermissionsPasswordPayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsPermission: { // field return type
    action: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    role: NexusGenRootTypes['UsersPermissionsRoleEntityResponse'] | null; // UsersPermissionsRoleEntityResponse
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsPermissionEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsPermission'] | null; // UsersPermissionsPermission
    id: string | null; // ID
  }
  UsersPermissionsPermissionEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsPermissionEntity'] | null; // UsersPermissionsPermissionEntity
  }
  UsersPermissionsPermissionEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsPermissionEntity'][]; // [UsersPermissionsPermissionEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UsersPermissionsPermissionRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsPermissionEntity'][]; // [UsersPermissionsPermissionEntity!]!
  }
  UsersPermissionsRole: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string | null; // String
    name: string; // String!
    permissions: NexusGenRootTypes['UsersPermissionsPermissionRelationResponseCollection'] | null; // UsersPermissionsPermissionRelationResponseCollection
    type: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    users: NexusGenRootTypes['UsersPermissionsUserRelationResponseCollection'] | null; // UsersPermissionsUserRelationResponseCollection
  }
  UsersPermissionsRoleEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsRole'] | null; // UsersPermissionsRole
    id: string | null; // ID
  }
  UsersPermissionsRoleEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsRoleEntity'] | null; // UsersPermissionsRoleEntity
  }
  UsersPermissionsRoleEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsRoleEntity'][]; // [UsersPermissionsRoleEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UsersPermissionsRoleRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsRoleEntity'][]; // [UsersPermissionsRoleEntity!]!
  }
  UsersPermissionsUpdateRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsUser: { // field return type
    blocked: boolean | null; // Boolean
    confirmed: boolean | null; // Boolean
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    dateOfBirth: NexusGenScalars['Date']; // Date!
    email: string; // String!
    provider: string | null; // String
    role: NexusGenRootTypes['UsersPermissionsRoleEntityResponse'] | null; // UsersPermissionsRoleEntityResponse
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    username: string; // String!
  }
  UsersPermissionsUserEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsUser'] | null; // UsersPermissionsUser
    id: string | null; // ID
  }
  UsersPermissionsUserEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsUserEntity'] | null; // UsersPermissionsUserEntity
  }
  UsersPermissionsUserEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsUserEntity'][]; // [UsersPermissionsUserEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UsersPermissionsUserRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsUserEntity'][]; // [UsersPermissionsUserEntity!]!
  }
}

export interface NexusGenFieldTypeNames {
  Banner: { // field return type name
    createdAt: 'DateTime'
    image: 'UploadFileEntityResponse'
    link: 'String'
    publishedAt: 'DateTime'
    subTitle: 'String'
    title: 'String'
    updatedAt: 'DateTime'
  }
  BannerEntity: { // field return type name
    attributes: 'Banner'
    id: 'ID'
  }
  BannerEntityResponse: { // field return type name
    data: 'BannerEntity'
  }
  BannerEntityResponseCollection: { // field return type name
    data: 'BannerEntity'
    meta: 'ResponseCollectionMeta'
  }
  BannerRelationResponseCollection: { // field return type name
    data: 'BannerEntity'
  }
  Category: { // field return type name
    categories: 'CategoryRelationResponseCollection'
    category: 'CategoryEntityResponse'
    createdAt: 'DateTime'
    image: 'UploadFileEntityResponse'
    metaData: 'JSON'
    name: 'String'
    products: 'ProductRelationResponseCollection'
    publishedAt: 'DateTime'
    tags: 'TagRelationResponseCollection'
    uid: 'String'
    updatedAt: 'DateTime'
  }
  CategoryEntity: { // field return type name
    attributes: 'Category'
    id: 'ID'
  }
  CategoryEntityResponse: { // field return type name
    data: 'CategoryEntity'
  }
  CategoryEntityResponseCollection: { // field return type name
    data: 'CategoryEntity'
    meta: 'ResponseCollectionMeta'
  }
  CategoryRelationResponseCollection: { // field return type name
    data: 'CategoryEntity'
  }
  ContentReleasesRelease: { // field return type name
    actions: 'ContentReleasesReleaseActionRelationResponseCollection'
    createdAt: 'DateTime'
    name: 'String'
    releasedAt: 'DateTime'
    updatedAt: 'DateTime'
  }
  ContentReleasesReleaseAction: { // field return type name
    contentType: 'String'
    createdAt: 'DateTime'
    entry: 'GenericMorph'
    release: 'ContentReleasesReleaseEntityResponse'
    type: 'ENUM_CONTENTRELEASESRELEASEACTION_TYPE'
    updatedAt: 'DateTime'
  }
  ContentReleasesReleaseActionEntity: { // field return type name
    attributes: 'ContentReleasesReleaseAction'
    id: 'ID'
  }
  ContentReleasesReleaseActionEntityResponse: { // field return type name
    data: 'ContentReleasesReleaseActionEntity'
  }
  ContentReleasesReleaseActionEntityResponseCollection: { // field return type name
    data: 'ContentReleasesReleaseActionEntity'
    meta: 'ResponseCollectionMeta'
  }
  ContentReleasesReleaseActionRelationResponseCollection: { // field return type name
    data: 'ContentReleasesReleaseActionEntity'
  }
  ContentReleasesReleaseEntity: { // field return type name
    attributes: 'ContentReleasesRelease'
    id: 'ID'
  }
  ContentReleasesReleaseEntityResponse: { // field return type name
    data: 'ContentReleasesReleaseEntity'
  }
  ContentReleasesReleaseEntityResponseCollection: { // field return type name
    data: 'ContentReleasesReleaseEntity'
    meta: 'ResponseCollectionMeta'
  }
  ContentReleasesReleaseRelationResponseCollection: { // field return type name
    data: 'ContentReleasesReleaseEntity'
  }
  Error: { // field return type name
    code: 'String'
    message: 'String'
  }
  I18NLocale: { // field return type name
    code: 'String'
    createdAt: 'DateTime'
    name: 'String'
    updatedAt: 'DateTime'
  }
  I18NLocaleEntity: { // field return type name
    attributes: 'I18NLocale'
    id: 'ID'
  }
  I18NLocaleEntityResponse: { // field return type name
    data: 'I18NLocaleEntity'
  }
  I18NLocaleEntityResponseCollection: { // field return type name
    data: 'I18NLocaleEntity'
    meta: 'ResponseCollectionMeta'
  }
  I18NLocaleRelationResponseCollection: { // field return type name
    data: 'I18NLocaleEntity'
  }
  Mutation: { // field return type name
    changePassword: 'UsersPermissionsLoginPayload'
    createBanner: 'BannerEntityResponse'
    createCategory: 'CategoryEntityResponse'
    createContentReleasesRelease: 'ContentReleasesReleaseEntityResponse'
    createContentReleasesReleaseAction: 'ContentReleasesReleaseActionEntityResponse'
    createProduct: 'ProductEntityResponse'
    createServiceAvailableAt: 'ServiceAvailableAtEntityResponse'
    createTag: 'TagEntityResponse'
    createTessssssst: 'TessssssstEntityResponse'
    createUploadFile: 'UploadFileEntityResponse'
    createUploadFolder: 'UploadFolderEntityResponse'
    createUsersPermissionsRole: 'UsersPermissionsCreateRolePayload'
    createUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    deleteBanner: 'BannerEntityResponse'
    deleteCategory: 'CategoryEntityResponse'
    deleteContentReleasesRelease: 'ContentReleasesReleaseEntityResponse'
    deleteContentReleasesReleaseAction: 'ContentReleasesReleaseActionEntityResponse'
    deleteProduct: 'ProductEntityResponse'
    deleteServiceAvailableAt: 'ServiceAvailableAtEntityResponse'
    deleteTag: 'TagEntityResponse'
    deleteTessssssst: 'TessssssstEntityResponse'
    deleteUploadFile: 'UploadFileEntityResponse'
    deleteUploadFolder: 'UploadFolderEntityResponse'
    deleteUsersPermissionsRole: 'UsersPermissionsDeleteRolePayload'
    deleteUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    emailConfirmation: 'UsersPermissionsLoginPayload'
    forgotPassword: 'UsersPermissionsPasswordPayload'
    login: 'UsersPermissionsLoginPayload'
    multipleUpload: 'UploadFileEntityResponse'
    register: 'UsersPermissionsLoginPayload'
    removeFile: 'UploadFileEntityResponse'
    resetPassword: 'UsersPermissionsLoginPayload'
    updateBanner: 'BannerEntityResponse'
    updateCategory: 'CategoryEntityResponse'
    updateContentReleasesRelease: 'ContentReleasesReleaseEntityResponse'
    updateContentReleasesReleaseAction: 'ContentReleasesReleaseActionEntityResponse'
    updateFileInfo: 'UploadFileEntityResponse'
    updateProduct: 'ProductEntityResponse'
    updateServiceAvailableAt: 'ServiceAvailableAtEntityResponse'
    updateTag: 'TagEntityResponse'
    updateTessssssst: 'TessssssstEntityResponse'
    updateUploadFile: 'UploadFileEntityResponse'
    updateUploadFolder: 'UploadFolderEntityResponse'
    updateUsersPermissionsRole: 'UsersPermissionsUpdateRolePayload'
    updateUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    upload: 'UploadFileEntityResponse'
  }
  Pagination: { // field return type name
    page: 'Int'
    pageCount: 'Int'
    pageSize: 'Int'
    total: 'Int'
  }
  Product: { // field return type name
    category: 'CategoryEntityResponse'
    createdAt: 'DateTime'
    description: 'String'
    discount: 'Float'
    mrp: 'Float'
    otherImages: 'UploadFileRelationResponseCollection'
    outOfStock: 'Boolean'
    productImage: 'UploadFileRelationResponseCollection'
    productInfo: 'String'
    publishedAt: 'DateTime'
    rating: 'Float'
    slug: 'String'
    sp: 'Float'
    tags: 'TagRelationResponseCollection'
    title: 'String'
    updatedAt: 'DateTime'
  }
  ProductEntity: { // field return type name
    attributes: 'Product'
    id: 'ID'
  }
  ProductEntityResponse: { // field return type name
    data: 'ProductEntity'
  }
  ProductEntityResponseCollection: { // field return type name
    data: 'ProductEntity'
    meta: 'ResponseCollectionMeta'
  }
  ProductRelationResponseCollection: { // field return type name
    data: 'ProductEntity'
  }
  Query: { // field return type name
    banner: 'BannerEntityResponse'
    banners: 'BannerEntityResponseCollection'
    categories: 'CategoryEntityResponseCollection'
    category: 'CategoryEntityResponse'
    contentReleasesRelease: 'ContentReleasesReleaseEntityResponse'
    contentReleasesReleaseAction: 'ContentReleasesReleaseActionEntityResponse'
    contentReleasesReleaseActions: 'ContentReleasesReleaseActionEntityResponseCollection'
    contentReleasesReleases: 'ContentReleasesReleaseEntityResponseCollection'
    i18NLocale: 'I18NLocaleEntityResponse'
    i18NLocales: 'I18NLocaleEntityResponseCollection'
    me: 'UsersPermissionsMe'
    product: 'ProductEntityResponse'
    products: 'ProductEntityResponseCollection'
    serviceAvailableAt: 'ServiceAvailableAtEntityResponse'
    serviceAvailableAts: 'ServiceAvailableAtEntityResponseCollection'
    tag: 'TagEntityResponse'
    tags: 'TagEntityResponseCollection'
    tessssssst: 'TessssssstEntityResponse'
    tesssssssts: 'TessssssstEntityResponseCollection'
    uploadFile: 'UploadFileEntityResponse'
    uploadFiles: 'UploadFileEntityResponseCollection'
    uploadFolder: 'UploadFolderEntityResponse'
    uploadFolders: 'UploadFolderEntityResponseCollection'
    usersPermissionsRole: 'UsersPermissionsRoleEntityResponse'
    usersPermissionsRoles: 'UsersPermissionsRoleEntityResponseCollection'
    usersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    usersPermissionsUsers: 'UsersPermissionsUserEntityResponseCollection'
  }
  ResponseCollectionMeta: { // field return type name
    pagination: 'Pagination'
  }
  ServiceAvailableAt: { // field return type name
    createdAt: 'DateTime'
    image: 'UploadFileEntityResponse'
    place: 'String'
    publishedAt: 'DateTime'
    uid: 'String'
    updatedAt: 'DateTime'
  }
  ServiceAvailableAtEntity: { // field return type name
    attributes: 'ServiceAvailableAt'
    id: 'ID'
  }
  ServiceAvailableAtEntityResponse: { // field return type name
    data: 'ServiceAvailableAtEntity'
  }
  ServiceAvailableAtEntityResponseCollection: { // field return type name
    data: 'ServiceAvailableAtEntity'
    meta: 'ResponseCollectionMeta'
  }
  ServiceAvailableAtRelationResponseCollection: { // field return type name
    data: 'ServiceAvailableAtEntity'
  }
  Tag: { // field return type name
    categories: 'CategoryRelationResponseCollection'
    createdAt: 'DateTime'
    icon: 'UploadFileEntityResponse'
    products: 'ProductRelationResponseCollection'
    publishedAt: 'DateTime'
    tagName: 'String'
    updatedAt: 'DateTime'
  }
  TagEntity: { // field return type name
    attributes: 'Tag'
    id: 'ID'
  }
  TagEntityResponse: { // field return type name
    data: 'TagEntity'
  }
  TagEntityResponseCollection: { // field return type name
    data: 'TagEntity'
    meta: 'ResponseCollectionMeta'
  }
  TagRelationResponseCollection: { // field return type name
    data: 'TagEntity'
  }
  Tessssssst: { // field return type name
    createdAt: 'DateTime'
    publishedAt: 'DateTime'
    test: 'String'
    updatedAt: 'DateTime'
  }
  TessssssstEntity: { // field return type name
    attributes: 'Tessssssst'
    id: 'ID'
  }
  TessssssstEntityResponse: { // field return type name
    data: 'TessssssstEntity'
  }
  TessssssstEntityResponseCollection: { // field return type name
    data: 'TessssssstEntity'
    meta: 'ResponseCollectionMeta'
  }
  TessssssstRelationResponseCollection: { // field return type name
    data: 'TessssssstEntity'
  }
  UploadFile: { // field return type name
    alternativeText: 'String'
    caption: 'String'
    createdAt: 'DateTime'
    ext: 'String'
    formats: 'JSON'
    hash: 'String'
    height: 'Int'
    mime: 'String'
    name: 'String'
    previewUrl: 'String'
    provider: 'String'
    provider_metadata: 'JSON'
    related: 'GenericMorph'
    size: 'Float'
    updatedAt: 'DateTime'
    url: 'String'
    width: 'Int'
  }
  UploadFileEntity: { // field return type name
    attributes: 'UploadFile'
    id: 'ID'
  }
  UploadFileEntityResponse: { // field return type name
    data: 'UploadFileEntity'
  }
  UploadFileEntityResponseCollection: { // field return type name
    data: 'UploadFileEntity'
    meta: 'ResponseCollectionMeta'
  }
  UploadFileRelationResponseCollection: { // field return type name
    data: 'UploadFileEntity'
  }
  UploadFolder: { // field return type name
    children: 'UploadFolderRelationResponseCollection'
    createdAt: 'DateTime'
    files: 'UploadFileRelationResponseCollection'
    name: 'String'
    parent: 'UploadFolderEntityResponse'
    path: 'String'
    pathId: 'Int'
    updatedAt: 'DateTime'
  }
  UploadFolderEntity: { // field return type name
    attributes: 'UploadFolder'
    id: 'ID'
  }
  UploadFolderEntityResponse: { // field return type name
    data: 'UploadFolderEntity'
  }
  UploadFolderEntityResponseCollection: { // field return type name
    data: 'UploadFolderEntity'
    meta: 'ResponseCollectionMeta'
  }
  UploadFolderRelationResponseCollection: { // field return type name
    data: 'UploadFolderEntity'
  }
  UsersPermissionsCreateRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsDeleteRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsLoginPayload: { // field return type name
    jwt: 'String'
    user: 'UsersPermissionsMe'
  }
  UsersPermissionsMe: { // field return type name
    blocked: 'Boolean'
    confirmed: 'Boolean'
    email: 'String'
    id: 'ID'
    role: 'UsersPermissionsMeRole'
    username: 'String'
  }
  UsersPermissionsMeRole: { // field return type name
    description: 'String'
    id: 'ID'
    name: 'String'
    type: 'String'
  }
  UsersPermissionsPasswordPayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsPermission: { // field return type name
    action: 'String'
    createdAt: 'DateTime'
    role: 'UsersPermissionsRoleEntityResponse'
    updatedAt: 'DateTime'
  }
  UsersPermissionsPermissionEntity: { // field return type name
    attributes: 'UsersPermissionsPermission'
    id: 'ID'
  }
  UsersPermissionsPermissionEntityResponse: { // field return type name
    data: 'UsersPermissionsPermissionEntity'
  }
  UsersPermissionsPermissionEntityResponseCollection: { // field return type name
    data: 'UsersPermissionsPermissionEntity'
    meta: 'ResponseCollectionMeta'
  }
  UsersPermissionsPermissionRelationResponseCollection: { // field return type name
    data: 'UsersPermissionsPermissionEntity'
  }
  UsersPermissionsRole: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    name: 'String'
    permissions: 'UsersPermissionsPermissionRelationResponseCollection'
    type: 'String'
    updatedAt: 'DateTime'
    users: 'UsersPermissionsUserRelationResponseCollection'
  }
  UsersPermissionsRoleEntity: { // field return type name
    attributes: 'UsersPermissionsRole'
    id: 'ID'
  }
  UsersPermissionsRoleEntityResponse: { // field return type name
    data: 'UsersPermissionsRoleEntity'
  }
  UsersPermissionsRoleEntityResponseCollection: { // field return type name
    data: 'UsersPermissionsRoleEntity'
    meta: 'ResponseCollectionMeta'
  }
  UsersPermissionsRoleRelationResponseCollection: { // field return type name
    data: 'UsersPermissionsRoleEntity'
  }
  UsersPermissionsUpdateRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsUser: { // field return type name
    blocked: 'Boolean'
    confirmed: 'Boolean'
    createdAt: 'DateTime'
    dateOfBirth: 'Date'
    email: 'String'
    provider: 'String'
    role: 'UsersPermissionsRoleEntityResponse'
    updatedAt: 'DateTime'
    username: 'String'
  }
  UsersPermissionsUserEntity: { // field return type name
    attributes: 'UsersPermissionsUser'
    id: 'ID'
  }
  UsersPermissionsUserEntityResponse: { // field return type name
    data: 'UsersPermissionsUserEntity'
  }
  UsersPermissionsUserEntityResponseCollection: { // field return type name
    data: 'UsersPermissionsUserEntity'
    meta: 'ResponseCollectionMeta'
  }
  UsersPermissionsUserRelationResponseCollection: { // field return type name
    data: 'UsersPermissionsUserEntity'
  }
}

export interface NexusGenArgTypes {
  Category: {
    categories: { // args
      filters?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    products: { // args
      filters?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    tags: { // args
      filters?: NexusGenInputs['TagFiltersInput'] | null; // TagFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
  }
  ContentReleasesRelease: {
    actions: { // args
      filters?: NexusGenInputs['ContentReleasesReleaseActionFiltersInput'] | null; // ContentReleasesReleaseActionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  Mutation: {
    changePassword: { // args
      currentPassword: string; // String!
      password: string; // String!
      passwordConfirmation: string; // String!
    }
    createBanner: { // args
      data: NexusGenInputs['BannerInput']; // BannerInput!
    }
    createCategory: { // args
      data: NexusGenInputs['CategoryInput']; // CategoryInput!
    }
    createContentReleasesRelease: { // args
      data: NexusGenInputs['ContentReleasesReleaseInput']; // ContentReleasesReleaseInput!
    }
    createContentReleasesReleaseAction: { // args
      data: NexusGenInputs['ContentReleasesReleaseActionInput']; // ContentReleasesReleaseActionInput!
    }
    createProduct: { // args
      data: NexusGenInputs['ProductInput']; // ProductInput!
    }
    createServiceAvailableAt: { // args
      data: NexusGenInputs['ServiceAvailableAtInput']; // ServiceAvailableAtInput!
    }
    createTag: { // args
      data: NexusGenInputs['TagInput']; // TagInput!
    }
    createTessssssst: { // args
      data: NexusGenInputs['TessssssstInput']; // TessssssstInput!
    }
    createUploadFile: { // args
      data: NexusGenInputs['UploadFileInput']; // UploadFileInput!
    }
    createUploadFolder: { // args
      data: NexusGenInputs['UploadFolderInput']; // UploadFolderInput!
    }
    createUsersPermissionsRole: { // args
      data: NexusGenInputs['UsersPermissionsRoleInput']; // UsersPermissionsRoleInput!
    }
    createUsersPermissionsUser: { // args
      data: NexusGenInputs['UsersPermissionsUserInput']; // UsersPermissionsUserInput!
    }
    deleteBanner: { // args
      id: string; // ID!
    }
    deleteCategory: { // args
      id: string; // ID!
    }
    deleteContentReleasesRelease: { // args
      id: string; // ID!
    }
    deleteContentReleasesReleaseAction: { // args
      id: string; // ID!
    }
    deleteProduct: { // args
      id: string; // ID!
    }
    deleteServiceAvailableAt: { // args
      id: string; // ID!
    }
    deleteTag: { // args
      id: string; // ID!
    }
    deleteTessssssst: { // args
      id: string; // ID!
    }
    deleteUploadFile: { // args
      id: string; // ID!
    }
    deleteUploadFolder: { // args
      id: string; // ID!
    }
    deleteUsersPermissionsRole: { // args
      id: string; // ID!
    }
    deleteUsersPermissionsUser: { // args
      id: string; // ID!
    }
    emailConfirmation: { // args
      confirmation: string; // String!
    }
    forgotPassword: { // args
      email: string; // String!
    }
    login: { // args
      input: NexusGenInputs['UsersPermissionsLoginInput']; // UsersPermissionsLoginInput!
    }
    multipleUpload: { // args
      field?: string | null; // String
      files: Array<NexusGenScalars['Upload'] | null>; // [Upload]!
      ref?: string | null; // String
      refId?: string | null; // ID
    }
    register: { // args
      input: NexusGenInputs['UsersPermissionsRegisterInput']; // UsersPermissionsRegisterInput!
    }
    removeFile: { // args
      id: string; // ID!
    }
    resetPassword: { // args
      code: string; // String!
      password: string; // String!
      passwordConfirmation: string; // String!
    }
    updateBanner: { // args
      data: NexusGenInputs['BannerInput']; // BannerInput!
      id: string; // ID!
    }
    updateCategory: { // args
      data: NexusGenInputs['CategoryInput']; // CategoryInput!
      id: string; // ID!
    }
    updateContentReleasesRelease: { // args
      data: NexusGenInputs['ContentReleasesReleaseInput']; // ContentReleasesReleaseInput!
      id: string; // ID!
    }
    updateContentReleasesReleaseAction: { // args
      data: NexusGenInputs['ContentReleasesReleaseActionInput']; // ContentReleasesReleaseActionInput!
      id: string; // ID!
    }
    updateFileInfo: { // args
      id: string; // ID!
      info?: NexusGenInputs['FileInfoInput'] | null; // FileInfoInput
    }
    updateProduct: { // args
      data: NexusGenInputs['ProductInput']; // ProductInput!
      id: string; // ID!
    }
    updateServiceAvailableAt: { // args
      data: NexusGenInputs['ServiceAvailableAtInput']; // ServiceAvailableAtInput!
      id: string; // ID!
    }
    updateTag: { // args
      data: NexusGenInputs['TagInput']; // TagInput!
      id: string; // ID!
    }
    updateTessssssst: { // args
      data: NexusGenInputs['TessssssstInput']; // TessssssstInput!
      id: string; // ID!
    }
    updateUploadFile: { // args
      data: NexusGenInputs['UploadFileInput']; // UploadFileInput!
      id: string; // ID!
    }
    updateUploadFolder: { // args
      data: NexusGenInputs['UploadFolderInput']; // UploadFolderInput!
      id: string; // ID!
    }
    updateUsersPermissionsRole: { // args
      data: NexusGenInputs['UsersPermissionsRoleInput']; // UsersPermissionsRoleInput!
      id: string; // ID!
    }
    updateUsersPermissionsUser: { // args
      data: NexusGenInputs['UsersPermissionsUserInput']; // UsersPermissionsUserInput!
      id: string; // ID!
    }
    upload: { // args
      field?: string | null; // String
      file: NexusGenScalars['Upload']; // Upload!
      info?: NexusGenInputs['FileInfoInput'] | null; // FileInfoInput
      ref?: string | null; // String
      refId?: string | null; // ID
    }
  }
  Product: {
    otherImages: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    productImage: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    tags: { // args
      filters?: NexusGenInputs['TagFiltersInput'] | null; // TagFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
  }
  Query: {
    banner: { // args
      id?: string | null; // ID
    }
    banners: { // args
      filters?: NexusGenInputs['BannerFiltersInput'] | null; // BannerFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    categories: { // args
      filters?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    category: { // args
      id?: string | null; // ID
    }
    contentReleasesRelease: { // args
      id?: string | null; // ID
    }
    contentReleasesReleaseAction: { // args
      id?: string | null; // ID
    }
    contentReleasesReleaseActions: { // args
      filters?: NexusGenInputs['ContentReleasesReleaseActionFiltersInput'] | null; // ContentReleasesReleaseActionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    contentReleasesReleases: { // args
      filters?: NexusGenInputs['ContentReleasesReleaseFiltersInput'] | null; // ContentReleasesReleaseFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    i18NLocale: { // args
      id?: string | null; // ID
    }
    i18NLocales: { // args
      filters?: NexusGenInputs['I18NLocaleFiltersInput'] | null; // I18NLocaleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    product: { // args
      id?: string | null; // ID
    }
    products: { // args
      filters?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    serviceAvailableAt: { // args
      id?: string | null; // ID
    }
    serviceAvailableAts: { // args
      filters?: NexusGenInputs['ServiceAvailableAtFiltersInput'] | null; // ServiceAvailableAtFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    tag: { // args
      id?: string | null; // ID
    }
    tags: { // args
      filters?: NexusGenInputs['TagFiltersInput'] | null; // TagFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    tessssssst: { // args
      id?: string | null; // ID
    }
    tesssssssts: { // args
      filters?: NexusGenInputs['TessssssstFiltersInput'] | null; // TessssssstFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    uploadFile: { // args
      id?: string | null; // ID
    }
    uploadFiles: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    uploadFolder: { // args
      id?: string | null; // ID
    }
    uploadFolders: { // args
      filters?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    usersPermissionsRole: { // args
      id?: string | null; // ID
    }
    usersPermissionsRoles: { // args
      filters?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    usersPermissionsUser: { // args
      id?: string | null; // ID
    }
    usersPermissionsUsers: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  Tag: {
    categories: { // args
      filters?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    products: { // args
      filters?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
  }
  UploadFolder: {
    children: { // args
      filters?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    files: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  UsersPermissionsRole: {
    permissions: { // args
      filters?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    users: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  GenericMorph: "Banner" | "Category" | "ContentReleasesRelease" | "ContentReleasesReleaseAction" | "I18NLocale" | "Product" | "ServiceAvailableAt" | "Tag" | "Tessssssst" | "UploadFile" | "UploadFolder" | "UsersPermissionsPermission" | "UsersPermissionsRole" | "UsersPermissionsUser"
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "GenericMorph";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}